name: Auto Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v4
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }}
          merge-method: merge  # Options: merge, squash, rebase
