name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 7 * * *" # Schedule for auto-updates
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate files in './profile-3d-contrib'
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push origin main
          fi
