name: GitHub Profile 3D Contrib

on:
  schedule: # 7:00am (UTC) == 0:00am (PDT)
    - cron: "0 7 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        env:
          PAT_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A .
          if git commit -m "generated"; then
            git push https://x-access-token:${{ secrets.PROFILE_3D_TOKEN }}@github.com/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY) HEAD:main
          fi
