name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 7 * * *" # Schedule for auto-updates
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate files in './profile-3d-contrib'
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated" || echo "No changes to commit"

      - name: Create or Checkout Branch
        run: |
          git checkout -b update-profile-3d-contrib || git checkout update-profile-3d-contrib

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
        run: |
          git push --force origin update-profile-3d-contrib

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PROFILE_3D_TOKEN }}
          branch: update-profile-3d-contrib
          commit-message: "generated"
          title: "Update GitHub Profile 3D Contribution"
          body: "Automated update of GitHub Profile 3D Contribution."
          labels: "automation"
          base: main
