name: GitHub Profile 3D Contrib

on:
  schedule:
    # Run at every 7am (UTC) = 0am (PDT)
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate files in './profile-3d-contrib'
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Create a new branch
        run: |
          git checkout -b update-profile-3d
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push --set-upstream origin update-profile-3d

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: update-profile-3d
          title: 'Update Profile 3D Contrib'
          body: 'Automated update of profile 3D contribution graph.'

      - name: Auto-merge pull request
        uses: pascalgn/github-action-auto-merge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: merge # or "squash" or "rebase"
