name: GitHub Profile 3D Contrib

on:
  schedule: 
    # Run at every 7am (UTC) = 0am (PDT)
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Disable Branch Protection
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.ADMIN_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/branches/main/protection \
            -d '{
              "required_status_checks":null,
              "enforce_admins":false,
              "required_pull_request_reviews":null,
              "restrictions":null
            }'
          echo "Branch protection disabled"
          sleep 10  # Wait for 10 seconds to ensure settings take effect

      - name: Gerate files in './profile-3d-contrib'
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push

      - name: Enable Branch Protection
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.ADMIN_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/branches/main/protection \
            -d '{
              "required_status_checks":null,
              "enforce_admins":false,
              "required_pull_request_reviews":{
                "dismiss_stale_reviews":true,
                "require_code_owner_reviews":false,
                "required_approving_review_count":0
              },
              "restrictions":null
            }'
          echo "Branch protection enabled"
