name: GitHub Stats Summary Cards

on:
  create:
  schedule:
    - cron: "0 0 * * *" # execute every 24 hours at midnight UTC
  workflow_dispatch:

  # Also run on every push on the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Stats Cards
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
