name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs to update at 0:00 AM
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate YouTube Cards
    # Allow the job to commit to the repository
    permissions:
      contents: write
      
    # Run the GitHub Readme YouTube Cards action
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v2
        
      - name: GitHub Readme YouTube Cards
        uses: DenverCoder1/github-readme-youtube-cards@1.7.0
        with:
          channel_id: UC7f92Y8DjOY1r8gL0Blt0gQ
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_NEW_API_KEY }}
          show_duration: true
          commit_message: "docs(readme): Update YouTube cards"
          readme_path: README.md
